### ISSUE TITLE
Sent Screen Duration Selection

### ISSUE THREAD

**Issue by QISPSK** [EyeSeeTea/SurveillanceCambodiaApp#107]
![image](https://cloud.githubusercontent.com/assets/17549893/25211348/10ba4352-25af-11e7-8784-210b1786574b.png)

Duration selection on the Sent Screen is too small to accommodate the available options in Khmer.

If possible, the duration selector for the Sent Screen should match the Monitor Module which would provide more room for the Khmer text.

**Comment by ifoche** [comment]
Sure, we can do it if you want. As discussed by email also with @rbeccapotter, in principle I'll wait for you to move it to ready column, to understand that this is something you want to do  after taking into consideration the complexity label and budget limitations

**Comment by QISPSK** [comment]
![screenshot_2017-05-02-09-57-16](https://cloud.githubusercontent.com/assets/17549893/25602777/bca6eb0a-2f20-11e7-9a4e-38d3032b929e.png)

@ifoche, the duration selector doesn't appear to have been updated to match the monitor module yet.

**Comment by ifoche** [comment]
Sorry @QISPSK I'm a bit lost here. The dropdown options aren't cut, right? Could you describe a bit more the problem?

**Comment by QISPSK** [comment]
![screenshot_2017-05-03-08-35-47](https://cloud.githubusercontent.com/assets/17549893/25645758/b5a4f098-2fdb-11e7-8f13-70f55af85b4c.png)

@ifoche, Sorry for the lack of clarity around this. If possible (for the sake of consistency) we'd like this period selector to match the one on the monitor module (pictured above). If that's too much work, we're happy to keep it as is.

**Comment by ifoche** [comment]
@QISPSK ok, I understand now, thank you for the clarification. I think it's more work than it may appear. The reason is that the file that's there waiting to process the data injected by another piece of code that searches in the internal DB for the data is structured in a table of 6 periods...so it's waiting for rows of 6 values. 6 weeks/months/days correspond perfectly with that scheme, but, for instance, selecting "this month" option would imply to show a single column of values. And how would we represent last week? 7 columns? or just 1 column too?

So the point is, it's doable, but we would need to establish how many columns do you want us to show for each option, and it implies a refactor in the layout, that would make me change the complexity label to high (more than 5 hours). Do you want us to go for it? In that case, how many columns do you want for each option and representing which sub-period?

**Comment by QISPSK** [comment]
@ifoche I think the above is something we will need to do in S7 as the 6 columns are a bit limiting, however, we simply want the same functionality when you select the period selector. 

In the monitor module, when you select the period (as in the image above), a floating context menu (I think that's the name?) appears to allow you to select the period. For the sake of consistency, it would be nice if the spinner on the sent screen was switched to a floating context menu like the one on the monitor module.

If this is a bit complicated, we will probably hold off as the fix you implemented did fix the overflow, but it would be nice to have them be the same, if possible.

**Comment by ifoche** [comment]
@QISPSK sorry, I see now what you mean. Yes, no problem, that's a very quick change. We'll include it for the next build

**Comment by QISPSK** [comment]
@ifoche Thanks for making this change. Could you increase the text size a bit? I'm having trouble selecting "last six days." Also, would it be possible to add the radio buttons that are present in the monitor module period selector?

**Comment by ifoche** [comment]
@QISPSK from a technical point of view, those 2 selectors are implemented in a very different way, and that's the reason why it's so tricky to give them the same exact appearance. The thing is that the sent surveys dropdown is a native android dropdown, while the monitor table is implemented using an HTML dropdown (the whole monitor table is an HTML). Making the font size bigger for usability is straightforward, and makes sense. However, providing the same exact appearance (by including also the radiobutton) can take a bit more time. Do you want us to go for both things or only for the text size? Thanks

**Comment by QISPSK** [comment]
@ifoche Ah OK, good to know! I think we can just go ahead with increasing the font size and go from there.
