### ISSUE TITLE
Blanks and Incorrect Ordering - Review Screen

### ISSUE THREAD

**Issue by QISPSK** [EyeSeeTea/SurveillanceCambodiaApp#111]
![image](https://cloud.githubusercontent.com/assets/17549893/25211656/642fde74-25b0-11e7-8695-c554fb56df32.png)

Changing answers mid-survey lead to inconsistent ordering of the review screen and, occasionally, blanks

**Comment by ifoche** [comment]
This is happening because to build that review screen we're looping across all the values defined for the survey. When you change a value in the middle, that can force any question that depends on that answer to be deleted (and that's why the blanks). As new values are added at the end of the other ones when we follow all of them we find the new one as the last and represent it accordingly. The way I would solve it is by asking each value for its question, and then sort all values according to their questions order, and not representing empty values. This is relatively easy to do, but some performance problem could appear, and that's why the complexity med label instead of the low one.

**Comment by QISPSK** [comment]
@ifoche the solution makes sense, go ahead and test it out and we can see if we run into any issues on our end

**Comment by ifoche** [comment]
Fine, we'll go for it

**Comment by QISPSK** [comment]
![screenshot_2017-05-02-09-38-43](https://cloud.githubusercontent.com/assets/17549893/25602544/0de48c90-2f1f-11e7-9636-9501d3a0d101.png)

@ifoche, Incorrect ordering still an issue when changing options after reaching the review screen.
