### ISSUE TITLE
Sent Screen "Last"

### ISSUE THREAD

**Issue by QISPSK** [EyeSeeTea/SurveillanceCambodiaApp#114]
![image](https://cloud.githubusercontent.com/assets/17549893/25211732/e9de3732-25b0-11e7-93e0-91cb2b406770.png)
![image](https://cloud.githubusercontent.com/assets/17549893/25211755/fefde77a-25b0-11e7-9a1e-151cddd8b6c3.png)

Sent Screen “Last 6 Months” does not include the current month, however the other “Last” options do

**Comment by ifoche** [comment]
Yes, the reason is explained in #108. If we change last 6 months to other options behaviour, there wouldn't be any way to represent current period data in monitoring. If we do it the other way around, we wouldn't be able to compare the number of cases with DHIS2 results. I think that maybe a bigger discussion about periods is needed. Does it make sense?

**Comment by ifoche** [comment]
BTW changing that behaviour to make the 3 options behave the same is very quick, so I will set this complexity label to low, but please take into account my previous comment
