### ISSUE TITLE
Coloring - Review Screen

### ISSUE THREAD

**Issue by QISPSK** [EyeSeeTea/SurveillanceCambodiaApp#117]
![image](https://cloud.githubusercontent.com/assets/17549893/25211909/e0318800-25b1-11e7-9004-80cf2e93bd2a.png)

Questions with the same color blend into each other on the review screen. Would it be possible to add a border around each item on the review screen? Or, perhaps use standardized branding for the review screen?

**Comment by ifoche** [comment]
In [this file](https://github.com/EyeSeeTea/SurveillanceCambodiaApp/blob/development/app/src/cambodia/assets/OptionAttributes.csv) you can review the hexadecimal color codes for all options. Changing the questions colors to make them always have a good contrast between them is as quick as changing those colors. Adding a border would be a bit slower (not very difficult) but introduce a modification compared to the rest of the MCS apps, so I wouldn't recommend it unless you also want to do it for all MCS apps...because little differences are more difficult to maintain than just having the same. Of course...everything can be done, is just a recommendation.

**Comment by QISPSK** [comment]
@ifoche If you could go ahead and change the hexadecimal color codes to have a better contrast, that would be great!

**Comment by QISPSK** [comment]
![screenshot_2017-05-02-09-38-43](https://cloud.githubusercontent.com/assets/17549893/25602628/b1166460-2f1f-11e7-8a00-9c18331e39d5.png)

Colors don't appear to have changed yet. Not sure which colors would produce good enough contrast while still keeping the look of the app consistent. Google's Material Design Spec/Color Tool may be able to help? https://material.io/guidelines/style/color.html#
