### ISSUE TITLE
The font for "(Pf)" and "(Pv)" seems to include a bunch of…

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/SurveillanceCambodiaApp#67]
Feedback from qispsk@gmail.com : The font for "(Pf)" and "(Pv)" seems to include a bunch of space (i.e. (   Pf)), can this be fixed?

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56d792f0e4d6010100721090/57586bc3bf09ff010013bc3a/8aa89cc9-100d-474a-9e29-d1604114aa09.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>25</td></tr><tr><td>Device type</td><td>LG-H324</td></tr><tr><td>Screen size</td><td>480</td></tr><tr><td>Screen size</td><td>480px by 786px</td></tr><tr><td>Battery</td><td>13% Unplugged</td></tr><tr><td>Memory free</td><td>128 MB / 711 MB</td></tr></table>

 [Link to buddybuild feedback from build 25](https://dashboard.buddybuild.com/apps/56d792f0e4d6010100721090/feedback?fid=575a7aa54f16310100427a11&bnum=25)

**Comment by rodmelia** [comment]
The screen shows the artwork provided by you in the SVG file, which includes those spaces. Could you please send updated SVG file with NO spaces?

**Comment by QISPSK** [comment]
Very odd, I retried to save the .svg but other elements seem to be missing - namely the AS/MQ pills. Not sure why this is thrown off in the .svg, but the other elements seem to be fixed, namely the "Reasons for Not Tested" thermometer, the "Referral" wording, and the spaces on the "Species" screen. 

Also, if possible, could you use the font and wording of the questions as it appears in the .svg? I'll also send along the font file we've been using in the design. 

For some reason it appears that GitHub won't accept the .zip I'm trying to attach. I'll send it to you, Rodolfo, over Skype. Let me know if anyone else needs the files.

**Comment by ifoche** [comment]
I let @rodmelia confirm but changing the app font could cause several alerts to split into 2 lines, or to display in a different way, that may be something you don't like. Is it not possible for you to use KhmerOS.ttf font in the images? Do you really prefer the font you're using in the pictures rather that the one used for the rest of the app?

**Comment by rodmelia** [comment]
@QISPSK - we believe that it is too risky to change the font on the app at this stage of the development. The app has used the same font since day #1. Changing the font will probably have un-intended effects, creating new misalignments or rendering issues, that will result in more last minute fixes. There is also copyright issues that we will have to check for. As far as we know,  this was not in the specs for S5 or any other previous release. We can add this to S6.

Alternatively, a safer option is for you to update the font of your artwork with the same font being used by the app.
