### ISSUE TITLE
Remove Phone GPS Tracking

### ISSUE THREAD

**Issue by QISPSK** [EyeSeeTea/SurveillanceCambodiaApp#93]
This was brought up awhile back, but we wanted to reopen this issue as a number of staff in our plantation program are concerned that GPS tracking may strain relationships on the plantations.

When we initially mapped the plantations for DHIS2, we had a large amount of push back from owners in terms of where we could pull GPS data from. Should owners learn that the application is collecting data wherever the MMW may be, they may refuse to work with us in the future or leave the program all together. 

Since we have GPS points for our providers in DHIS2 (though they're not quite perfect yet...) and can use them by sorting for the correct subnational level, is it possible to remove the GPS feature of the application completely?

**Comment by rodmelia** [comment]
Are you asking to remove GPS capturing all together for all OUs?
Or to remove GPS capturing selectively?

**Comment by QISPSK** [comment]
Is it possible to remove it for select OUs? If so, I guess that would work, but since we have this information already in DHIS2, it may make sense to completely get rid of GPS tracking, especially if it would speed up the application or if incorrect GPS information is leading to the sending of blank data.

**Comment by ifoche** [comment]
Hi @QISPSK, I think blanks are not related to GPS coordinates, as I've seen blanks with GPS coordinates in QIS_test_int from a couple of days ago. However, we can of course deactivate GPS if that's best for you. It could be done only over a subgroup of OUs, but how do we tell the app that an specific OU is GPS traceable or not? The only thing that I can think about is by using an OU attribute, but that is something very risky to introduce at this stage (in my opinion). So wouldn't do the trick by simply deactivate it by default but keeping a setting to activate it for the OUs that want to do it? Otherwise, it would be also simple to remove it completely for every OU. What do you think?

**Comment by rodmelia** [comment]
We cannot remove the GPS capture coordinates until next version - this is a major change, and his the sort of changes the make the application unstable. 

@cristinaelle : KH is asking to remove GPS capture coordinates - what do you think?

**Comment by QISPSK** [comment]
@ifoche Unless this speeds up the app considerably, I don't think this is something we need to remove going forward as we have had zero complaints. While some GPS points have come through incorrectly, it may serve a purpose later down the road and is particularly useful for programs that have yet to map out all of their providers (and may be useful for us to ensure the providers we have mapped have been mapped correctly). Moving this to done.
